package pixel;

/**
 * OpenAPI 3.0 spesifikasyonu uretici.
 * OpenAPI 3.0 specification generator.
 *
 * Kayitli rotalari tarar ve `GET /openapi.json` gibi bir yolda
 * sunulabilecek bir JSON dokumani olusturur:
 * Scans registered routes and produces a JSON document suitable for
 * serving under a path such as `GET /openapi.json`:
 *
 * ```haxe
 * app.docs(); // GET /openapi.json otomatik eklenir / is registered automatically
 * ```
 *
 * `app.describe("GET", "/api/users/:id", "Tek kullanici")` ile rota
 * aciklamasi eklenebilir / Route summaries can be attached via
 * `app.describe(...)`.
 */
class OpenApi {
    public var title:String;
    public var version:String;
    public var description:String;

    public function new(?title:String = "Pixel Api", ?version:String = "0.3.0", ?description:String = null) {
        this.title = title == null ? "Pixel Api" : title;
        this.version = version == null ? "0.3.0" : version;
        this.description = description == null
            ? "pixel-haxe tarafindan uretildi / generated by pixel-haxe"
            : description;
    }

    /**
     * Uygulamanin rotalarindan OpenAPI 3.0 dokumani uretir.
     * Builds an OpenAPI 3.0 document from the app's routes.
     */
    public function spec(app:Pixel):Dynamic {
        var paths:Dynamic = {};
        for (r in app.router.routes) {
            if (r.method == "*") continue;
            if (r.segments.indexOf("*") >= 0) continue; // catch-all rotalar belgelenmez / catch-alls are not documented
            var p = toOpenApiPath(r.pattern);
            var item:Dynamic = Reflect.field(paths, p);
            if (item == null) {
                item = {};
                Reflect.setField(paths, p, item);
            }
            var op:Dynamic = {
                summary: r.summary == null ? r.toString() : r.summary,
                tags: r.tags,
                parameters: parametersOf(r),
                responses: {
                    "200": {description: "Success / Basarili"}
                }
            };
            Reflect.setField(item, r.method.toLowerCase(), op);
        }
        return {
            openapi: "3.0.0",
            info: {
                title: title,
                version: version,
                description: description
            },
            paths: paths
        };
    }

    /**
     * `:param` segmentlerini OpenAPI `{param}` bicimine cevirir.
     * Converts `:param` segments to OpenAPI `{param}` syntax.
     */
    public static function toOpenApiPath(pattern:String):String {
        var parts = Router.splitPath(Router.normPath(pattern));
        var out = [];
        for (s in parts) {
            if (s.length > 1 && s.charAt(0) == ":") {
                out.push("{" + s.substr(1) + "}");
            } else {
                out.push(s);
            }
        }
        return "/" + out.join("/");
    }

    static function parametersOf(r:Route):Array<Dynamic> {
        var out = [];
        for (s in r.segments) {
            if (s.length > 1 && s.charAt(0) == ":") {
                out.push({
                    name: s.substr(1),
                    "in": "path",
                    required: true,
                    schema: {"type": "string"}
                });
            }
        }
        return out;
    }
}
